### ISSUE TITLE
You must define an TOKBOX_API_KEY and TOKBOX_SECRET in the run-demo file

### ISSUE THREAD

**Issue by gaurvivek** [opentok/learning-opentok-php#13]
I added my api key and secret in run-demo file.

#!/bin/sh

if [ -z "$TOKBOX_API_KEY" ] || [ -z "$TOKBOX_SECRET" ]
then
   export TOKBOX_API_KEY=00000000
   export TOKBOX_SECRET=000000000000000000000000000
fi

if [ -d "storage" ]
then
  rm -rf storage/
fi

php -S 0.0.0.0:8080 -t web web/index.php

and then run run-demo file in windows cmd. But it still saying 
You must define an TOKBOX_API_KEY and TOKBOX_SECRET in the run-demo file

**Comment by jleaders** [comment]
New to tokbox, but why is an API key & Secret needed if we have all the server code? Can't we instrument & run our own server without phoning home to tokbox?

**Comment by MichaelJolley** [comment]
Closed as stale. If this issue persists, feel free to open a new issue.
