### ISSUE TITLE
Works on localhost but not using IP from the same PC

### ISSUE THREAD

**Issue by CatsNipYummy** [opentok/learning-opentok-php#16]
I'm trying to access the server using my PC's IP -> 192.168.0.10:8080 but that fails. localhost:8080 works fine. Do I need to make changes to some config file for this to work?

**Comment by jleaders** [comment]
If you `nmap` your IP does it show that port open from another device? If not it may be a firewall blocking it

**Comment by MichaelJolley** [comment]
Closed as stale. If this issue persists, feel free to open a new issue.
