### ISSUE TITLE
Default 404 page should explain how to continue with tutorial

### ISSUE THREAD

**Issue by aoberoi** [opentok/learning-opentok-php#4]
Right now the default route (`/`) serves a plain 404 page not found template. It creates confusion for the first time user who doesn't know if she actually successfully deployed the server.

**Comment by xia50** [comment]
The keroku is bugged, I got the same thing and then I forked this repo to my own, adding in the API_KEY etc. and redeploy on the heroku, later on I git clone the repo on heroku and in either way the repos are empty!!!, There is no way that you can get something other than 404 shows up.

I think no one is using OpenTok and there are lacking of maintenance.

**Comment by diegojerezb** [comment]
Anyone has been able to deploy OpenTok in Heroku? The same 404 page here...

**Comment by davemun** [comment]
You can't get anything visually meaningful from trying to open a web page against this deployment. This is the PHP back-end. You should be running the Web front-end here: https://github.com/opentok/learning-opentok-web against this back-end.

**Comment by jeffswartz** [comment]
Fixed with https://github.com/opentok/learning-opentok-php/commit/9c87f96f8aa48b95affb68a68d8852896f37a45c.
