### ISSUE TITLE
crash trying to render view.php

### ISSUE THREAD

**Issue by mpoisot** [opentok/learning-opentok-php#5]
I used the learning-opentok-web archive branch to test out a 2 user video archive. I clicked "archive", "stop" then "view". The view button loaded a new page, presumably because the archive wasn't yet ready to view. But that page crashed with the following message:

```
exception 'RuntimeException' with message 'View cannot render `view.php` because the template does not exist' in /Users/marcel/proj/tmp/learning-opentok-php/vendor/slim/slim/Slim/View.php:272
```

**Comment by dennislixin** [comment]
I had the same issue.  The fix is following:

1. Go to `\web\index.html`
2. change `'templates.path' => '../templates'` to `'templates.path' => '/../templates'`

**Comment by dennislixin** [comment]
To the project owner:
Can I create pull request for this bug?

**Comment by jeffswartz** [comment]
We found that this did not fix the issue:
`'templates.path' => '/../templates' `
This fixed it: 
` 'templates.path' => __DIR__.'/../templates'`
